### PR TITLE
Update TurtleGold config

### PR DESCRIPTION
**Pull request by bobbieltd**
- Revert unlock window back to 120 (consensus breaking)
- Update 1st block timestamp (print_block 2)
- Applying tx extra limit and sign validation from the start (new coin can take effect from 0).

### CODE REVIEW

**Comment by MaayanSG** [comment]
If you want to hard fork the coin, then do it on ur own GitHub.

**Comment by bobbieltd** [comment]
Dude ! Fork what !?!?  Well, you can re-read this PR later.

**Comment by MaayanSG** [comment]
I read it... looks like you’re trying to make a fork. Either way, we don’t want this stuff on our coin... so I’m not reopening the PR!

**Comment by bobbieltd** [comment]
No problem. Perfect !

**Pull request closed without merging**
